/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "stdint.h"
#define RCC 0x40021000
#define GPIO_PORTA 0x40010800
#define APB2ENR  *(volatile uint32_t *)(RCC+0x18)
#define CRH *(volatile uint32_t *)(GPIO_PORTA+0x04)
#define ODR *(volatile uint32_t *)(GPIO_PORTA+0x0C)
int main()
{
	int i;
	APB2ENR|=(1<<2);
	CRH&=0xFF0FFFFF;
	CRH|=0x00200000;
	while(1){
		ODR|=(1<<13);
		for(i=0;i<1000;i++);
			ODR&=~(1<<13);
		for(i=0;i<1000;i++);

	}







}

